##MOUNT DRIVE

In [52]:
from google.colab import drive
drive.mount('/content/gdrive')
import os
os.chdir("/content/gdrive/My Drive/HW1_ML")
import numpy as np
from util import get_mnist_data
from logistic_np import add_one, LogisticClassifier
from softmax_np import *

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


##SOFTMAX_NP

###TODO 2.1: Chuẩn hóa dữ liệu

In [53]:
train_x, train_y, val_x, val_y, test_x, test_y = get_mnist_data()
train_x, val_x, test_x = normalize(train_x, val_x, test_x)

Reading fashion MNIST data...
<class 'numpy.ndarray'>


In [54]:
train_x[0][0:10]

array([-0.8080229, -0.8080229, -0.8080229, -0.8080229, -0.8080229,
       -0.8080229, -0.8080229, -0.8080229, -0.8080229, -0.8080229],
      dtype=float32)

###TODO 2.2: Tạo ma trận one-hot

In [55]:
train_y = create_one_hot(train_y)
val_y = create_one_hot(val_y)
test_y = create_one_hot(test_y)

In [56]:
train_y

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

###TODO 2.3 - Tính các giá trị phân loại 

In [57]:
train_x = add_one(train_x)
val_x = add_one(val_x)
test_x = add_one(test_x)

num_feature = train_x.shape[1]
dec_classifier = SoftmaxClassifier((num_feature, 10))
train_y_hat = dec_classifier.feed_forward(train_x)

In [58]:
train_y_hat

array([[0.01836677, 0.00562935, 0.4799791 , ..., 0.11505976, 0.01126952,
        0.18803774],
       [0.09392317, 0.29645027, 0.07178385, ..., 0.06257693, 0.00265919,
        0.0420562 ],
       [0.17111511, 0.08333466, 0.23802922, ..., 0.02260882, 0.01031703,
        0.30127021],
       ...,
       [0.09975072, 0.62495118, 0.07973969, ..., 0.01224637, 0.00335084,
        0.00283778],
       [0.0485257 , 0.14742686, 0.26491249, ..., 0.03741206, 0.02057914,
        0.00451708],
       [0.02496634, 0.03876298, 0.21078959, ..., 0.19762442, 0.15268714,
        0.0523463 ]])

###TODO 2.4 - Tính độ lỗi 

In [59]:
train_loss = dec_classifier.compute_loss(train_y, train_y_hat)

In [60]:
train_loss

2.4498879135219123

###TODO 2.5 - Tính đạo hàm 

In [61]:
grad = dec_classifier.get_grad(train_x, train_y, train_y_hat)

In [62]:
grad

array([[ 0.00226223, -0.06816431, -0.08946164, ...,  0.01098402,
         0.06573749, -0.01184816],
       [ 0.00227209, -0.06815997, -0.08944951, ...,  0.01098782,
         0.06573603, -0.01184509],
       [ 0.00213754, -0.06809155, -0.08942523, ...,  0.01100249,
         0.0657342 , -0.01183654],
       ...,
       [ 0.00295915, -0.06759032, -0.08893543, ...,  0.01154943,
         0.06416927, -0.01252872],
       [ 0.00220788, -0.0681487 , -0.08943737, ...,  0.01099741,
         0.06572753, -0.0118704 ],
       [-0.00280272,  0.08436028,  0.11071777, ..., -0.01359363,
        -0.08135585,  0.01466318]])

###TODO 2.6 - Đề xuất điều kiện dừng

###TODO 2.7 - Đánh giá mô hình phân loại 

In [63]:
!python3 softmax_np.py

Reading fashion MNIST data...
<class 'numpy.ndarray'>
Confusion matrix:
[[0.93 0.   0.02 0.05 0.   0.   0.02 0.   0.   0.  ]
 [0.02 0.95 0.   0.05 0.   0.   0.   0.   0.   0.  ]
 [0.02 0.   0.61 0.05 0.23 0.   0.09 0.   0.   0.  ]
 [0.05 0.03 0.   0.8  0.02 0.   0.04 0.   0.   0.  ]
 [0.   0.   0.09 0.05 0.74 0.   0.09 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.92 0.   0.08 0.   0.  ]
 [0.22 0.   0.11 0.03 0.23 0.   0.45 0.   0.02 0.  ]
 [0.   0.   0.   0.   0.   0.06 0.   0.84 0.   0.1 ]
 [0.   0.   0.   0.03 0.02 0.04 0.   0.   0.93 0.  ]
 [0.   0.   0.   0.   0.   0.02 0.   0.   0.   0.98]]
Diagonal values:
[0.93 0.95 0.61 0.8  0.74 0.92 0.45 0.84 0.93 0.98]


##TEST SOFTMAX_NP

In [64]:
!python3 unit_test.py

Please enter 0 for logistic or 1 for softmax: 1
Running logistic np unit test...
Reading fashion MNIST data...
<class 'numpy.ndarray'>
Testing normalize: Passed.
----------------------------------------
Testing create_one_hot: Passed.
----------------------------------------
Testing feed_forward / softmax: Passed.
----------------------------------------
Testing compute_loss: Passed.
----------------------------------------
Testing get_grad: Passed.
----------------------------------------
Testing feed_forward / softmax: Passed.
----------------------------------------
Testing compute_loss: Passed.
----------------------------------------
Testing get_grad: Passed.
----------------------------------------
Testing feed_forward / softmax: Passed.
----------------------------------------
Testing compute_loss: Passed.
----------------------------------------
Testing get_grad: Passed.
----------------------------------------
Testing feed_forward / softmax: Passed.
---------------------------

##SOFTMAX_TF

In [65]:
import tensorflow as tf
np.random.seed(2020)
tf.compat.v1.set_random_seed(2020)
train_x, train_y, val_x, val_y, test_x, test_y = get_mnist_data()
train_y = create_one_hot(train_y)
val_y = create_one_hot(val_y)
test_y = create_one_hot(test_y)
train_x, val_x, test_x = normalize(train_x, val_x, test_x)
train_x = add_one(train_x) 
val_x = add_one(val_x)
test_x = add_one(test_x)

Reading fashion MNIST data...
<class 'numpy.ndarray'>


###TODO 2.8 - Tạo TF place holders, variables, cập nhật w

In [66]:
m, n = train_x.shape
num_epoch = 100
tf.compat.v1.disable_eager_execution()
tf.compat.v1.disable_v2_behavior()
x = tf.compat.v1.placeholder(tf.float32, shape=(None, n))
y = tf.compat.v1.placeholder(tf.float32, shape=(None, 10))

In [67]:
w = tf.Variable(tf.ones([n, 1]), dtype=tf.float32)

###TODO 2.9 & 2.10: Tạo toán tử feed forward & Tính độ lỗi 

In [68]:
pred = tf.matmul(x, w)
cost = tf.nn.softmax_cross_entropy_with_logits(logits = pred, labels = y)

###TODO 2.8: SGD optimizer

In [69]:
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.002).minimize(cost)

###TODO 2.11 - Tạo điều kiện dừng 
